#' @title  Initialize Expred module
#' @description Initialize Expred analysis. It can generate an R6 class object
#'     integrating all the analysis information.
#' @usage InitEX()
#' @param PID chr. Program ID. It must be the same with the PID generated by InitEX.
#' @param FileDirIn "default"
#' @param FileDirOut "default"
#'
#' @details Expred module is designed to integrate the multi-group data to predict the incidence risk.
#'     It mainly aims to construct various stacked generalization(SG) models to predict the probability
#'     of outcome incidence, as well as providing the statistical explanation. In addition, the module can provide
#'     visualization plots with high quality of the final calculation results to make it easier for users to understand.
#' @return An R6 class object.
#' @export
#' @examples eSet = InitEX(PID = "EX", FileDirIn = "default", FileDirOut = "default")
#' @author Guohuan Zhang, Yuting Wang, Bin Wang (corresponding author)
InitEX <- function(PID = "default",
                   FileDirIn = "default",
                   FileDirOut = "default"
                     ){
  tictoc::tic()

  lubridate::now() %>%
    stringr::str_replace_all(":",".") %>%
    stringr::str_replace_all("-",".") -> NowTime

# create R6 class eSet ----------------------------------------------------
    eSet <- R6::R6Class(
      "eSet",
      public = list(
        PID = NULL,
        EpiDesign = NULL,
        FileDirIn = NULL,
        FileDirOut = NULL,
        VarsDel = NULL,
        Expo = list(Data = NULL,
                    Voca = NULL),
        ExcecutionLog = NULL,
        RCommandLog = NULL,

        AddLog = function(x){
          self$ExcecutionLog = c(self$ExcecutionLog,
                                 stringr::str_c(x))},

        AddCommand = function(x){
          self$RCommandLog = c(self$RCommandLog,
                               stringr::str_c(x))},

        initialize = function(FileDirIn,
                              FileDirOut) {
          self$FileDirIn = FileDirIn
          self$FileDirOut = FileDirOut}
        ),

      lock_class = FALSE,
      lock_objects = FALSE
      )

  eSet <- eSet$new(FileDirIn = FileDirIn,
                   FileDirOut = FileDirOut)

  # generate default PID
    if(PID != "default"){
      eSet$PID = PID
      }else{
      eSet$PID <- stringr::str_c(lubridate::now() %>%
                         stringr::str_remove_all(" ") %>%
                         stringr::str_remove_all("-") %>%
                         stringr::str_remove_all(":") %>%
                         stringr::str_sub(9,-1),
                       collapse = "") %>%
        stringr::str_c(sample(c("A","B","C","D","E","F","G","H","J","K","L","M","N","P","Q","R","S","T","U","V","W","X","Y","Z"),
                              6, replace = TRUE) %>%
                         stringr::str_c(collapse = ""))
      }

  # initialize the folder ---------------------------------------------------
  if(FileDirIn == "default"){
    stringr::str_c(getwd(),
                   "/input_",
                   eSet$PID) -> eSet$FileDirIn

    if(!file.exists(eSet$FileDirIn)){
      dir.create(eSet$FileDirIn)
    }
  }else if(!file.exists(FileDirIn)){
    stringr::str_c(FileDirIn,
                   "/input_",
                   eSet$PID) -> eSet$FileDirIn
    dir.create(eSet$FileDirIn)
  }


  if(FileDirOut == "default"){
    stringr::str_c(getwd(),
                   "/output_",
                   eSet$PID) -> eSet$FileDirOut

    if(!file.exists(eSet$FileDirOut)){
      dir.create(eSet$FileDirOut)
    }
  }else if(!file.exists(FileDirOut)){
    stringr::str_c(FileDirOut,
                   "/output_",
                   eSet$PID) -> eSet$FileDirOut
    dir.create(eSet$FileDirOut)
  }


  # save R command log ----
  eSet$RCommandLog <- eSet$AddCommand(stringr::str_c("eSet <- InitMo(PID = Any ID your like, FileDirOut = Any output file directory your like)"))

  eSet$RCommandLog %>%
    as_tibble() %>%
    purrr::set_names("R commands") %>%
    data.table::fwrite(stringr::str_c(eSet$FileDirOut,"/rcommands log.txt"))

  # save log ----
  message("Complete initializing the MultiOmic module. \n", NowTime, "\n")

  eSet$ExcecutionLog  <- eSet$AddLog(stringr::str_c("Complete initializing the MultiOmic module.",
                                                    NowTime))
  quiet(eSet$ExcecutionLog %>%
          as_tibble() %>%
          purrr::set_names("running log") %>%
          data.table::fwrite(stringr::str_c(eSet$FileDirOut,"/running log.txt"))
  )

  # save eSet ----
  eSet %>%
    save(file = str_c(eSet$FileDirOut,"/eSet.Rdata"))


  tictoc::toc()

  return(eSet)
}
